### ISSUE TITLE
TO-DO LIST

### ISSUE THREAD

**Issue by frangejt123** [frangejt123/sales.ramx.store#5]
- [x]  Allow agent and admin to edit order
- [x]  Allow agent to add delivery date
- [x]  Generate Transaction ID
- [x]  Add remarks field
- [x]  If tag na for delivery. Pwede ma untag and balik sa pending for editing.
- [x]  Sort Transaction per delivery date
- [x]  add inventory count per item sa masterfile. Then ga subtract everytime mag punch
- [x]  Search Per Customer,
- [x]  add field facebook name
- [x]  put field to attach image. Para ma attach map sng customer kung may record na
- [x]  Add customer ID. Auto generate. Kamo na bahala

- [ ] Tag SO as paid. With Remarks (Gcash, BPI, Metrobank, etc.)
- [ ] Report: Summary of Orders Per Delivery date Per Item, with price and qty
- [ ] Add Remarks - SO Specific
- [ ] Create Sales Agent ID. Display it sa SO Details. But not when printing
- [ ] Add View Customer Masterfile. 
- [ ] SO can be updated only by the sales agent that created it. Admin can also edit
- [ ] Generate Customer ID. It will be given to the customer so that they can use it for future transactions.
- [ ]  When Taking Order using Web POS. pwede may view sa kilid na pwede ma copy paste sa messenger. Amo ni nga format
        Name:
	Address:
	Contact Number
	Mode of Payment:
	Orders:
	Remarks:

**Comment by frangejt123** [comment]
@lordroseman
